name: 'C++ CI'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ubuntu:
    name: Ubuntu build & test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Run tests
        run: ctest --test-dir build -C Release --output-on-failure

  build-windows:
    name: Windows build & test
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Run tests
        run: ctest --test-dir build -C Release --output-on-failure

  create-release:
    needs: [build-ubuntu, build-windows]
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
          files: |
            ./artifacts/ubuntu-package/*.deb
            ./artifacts/windows-exe/ip_filter.exe      